type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.grid_import
      production: sensor.grid_export
    display_state: two_way
    color_circle: true
  solar:
    entity: sensor.solar_power
  battery:
    entity:
      consumption: sensor.battery_charge
      production: sensor.battery_discharge
    state_of_charge: sensor.battery_state_of_charge
    display_state: two_way
    color_circle: true
  home:
    color_icon: true
  individual:
    - entity: sensor.eps_power
      secondary_info: {}
      icon: mdi:account
      name: eps
      color_value: true
      display_zero: true
      color_icon: true
watt_threshold: 10000
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
clickable_entities: true
